version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/Toronto
  open-pull-requests-limit: 10
  assignees:
  - WildCard65
  labels:
  - "\U0001F916 Dependency update"
  versioning-strategy: increase-if-necessary
