version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Toronto
    open-pull-requests-limit: 10
    assignees:
      - WildCard65
    labels:
      - "\U0001F916 Dependency update"
      - AUTOMERGE
    versioning-strategy: increase
    commit-message:
      prefix: "#|DEPS|# "
      prefix-development: "#|DEV DEPS|# "
      include: scope
    rebase-strategy: auto
