name: "Invoke AMBuild"
description: "A GitHub action dedicated to invoking AMBuild."
branding:
  icon: "check-square"
  color: "green"
inputs:
  build-folder:
    description: "The name of the folder to execute the build in."
    required: true
    default: "build"
  project-root:
    description: "The root directory containing your 'configure.py'."
    required: true
    default: "./"
  configure-args:
    description: "Additional arguments to supply to 'configure.py'."
    required: false
    default: ""
  delete-build:
    description: "Should this action delete the build folder after the build completes?"
    required: false
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
