name: "AMBuild"
description: "A GitHub action dedicated to invoking AMBuild."
inputs:
  auto-install:
    description: "Should this action automatically install a copy of AMBuild?"
    required: true
    default: "true"
  build-folder:
    description: "The name of the folder to execute the build in."
    required: true
    default: "build"
  project-root:
    description: "The root directory containing your 'configure.py'."
    required: true
    default: "./"
  delete-build:
    description: "Should this action delete the build folder after the build completes?"
    required: false
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
