name: Pull Request AUTOMERGE
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - unlocked
  pull_request_review:
    types:
      - dismissed
      - submitted
  check_suite:
    types:
      - completed
      - rerequested
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: squalrus/merge-bot@v0.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: true
          checks_enabled: true
          labels: AUTOMERGE
          blocking_labels: DO NOT MERGE
          method: squash
