name: Pull Request AUTOMERGE
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - unlocked
  pull_request_review:
    types:
      - dismissed
      - submitted
  check_suite:
    types:
      - completed
      - rerequested
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: AUTOMERGE,!DO NOT MERGE
          MERGE_REMOVE_LABELS: AUTOMERGE
          MERGE_METHOD: squash
