name: ESLint
on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          includeGlob: src/*.ts
          configFile: package.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
