# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GH Action Test
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Update packaging tools
      run: |
        python -m pip install --upgrade pip setuptools
        pip install wheel
    - name: Activate Visual Studio DevCMD
      if: ${{ matrix.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1.3.0
      with:
        arch: x64
    - name: Run the action
      uses: ./
      with:
        delete-build: true
